i2s_audio:
  i2s_lrclk_pin: "${i2s_lrclk_pin}"  # WS
  i2s_bclk_pin: "${i2s_bclk_pin}"  # SCK

microphone:
  - platform: i2s_audio
    id: mic_i2s
    channel: left
    adc_type: external
    i2s_din_pin: "${i2s_din_pin}"  # SD
    pdm: false

media_player:
  - platform: i2s_audio
    id: media_player_i2s
    name: ESPHome I2S Media Player
    dac_type: external
    i2s_dout_pin: "${i2s_dout_pin}"
    mode: stereo

voice_assistant:
  id: va
  microphone: mic_i2s
  media_player: media_player_i2s
  noise_suppression_level: 2
  auto_gain: 31dBFS
  volume_multiplier: 2.0
  # on_tts_end:
  #   - delay: 100ms
  #   - script.execute: reset_led
  # on_error:
  #   - light.turn_on:
  #       id: led
  #       blue: 0%
  #       red: 100%
  #       green: 0%
  #       brightness: 100%
  #       effect: none
  #   - delay: 1s
  #   - script.execute: reset_led
  #   - script.wait: reset_led
  #   - lambda: |-
  #       if (code == "wake-provider-missing" || code == "wake-engine-missing") {
  #         id(use_wake_word).turn_off();
  #       }



esphome:
  on_boot:
    - priority: -100
      then:
        - wait_until: api.connected
        - delay: 1s
        - voice_assistant.start_continuous:
        - light.turn_on:
            id: led
            blue: 100%
            red: 0%
            green: 100%
            brightness: 10%
            effect: pulse
